### ISSUE TITLE
Implement HEAD requests for the file resource

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-accounting#34]
This allows the client to check for modified files.

**Comment by julianseeger** [comment]
Actually, I think I overvalued this. Just executing a GET request, using its headers and only stream its body if it got modified ( checked by `Last-Modified`) should do the job and save an additional request.
If that causes wasted downloads between the S3 and the storage-/accounting-server, support for `If-Modified-Since` should fix it and would be preferable over a HEAD request.
Or... did I miss something? ;)

**Comment by audax** [comment]
Sounds good.
