### ISSUE TITLE
Confirmation of the mail address should be only needed after 7 days

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-accounting#41]
Given a user that just registered
And did not confirm the mail address
Then the user should be able to login

Given a user that registered at least 7 days ago
And did not confirm his mail address
Then the should should not be able to login
And a confirmation mail should be send

Given a user that registered at least 7 days ago
And did not confirm his mail address
And already received an additional confirmation mail today
Then he should not be able to login
And no additional confirmation mail should be send

**Comment by julianseeger** [comment]
Gherkin ftw. ;)
Today, the question came up why we need the users username AND email address. The answer was that the email is optional so that a user may add an email address to be able to recover his password or may not add an email address to be more anonymous.
Given a user needs to confirm his mail address it sounds implicitly like the email address is required, which in return reopens the question why we need both. So ... why do we need both?

**Comment by audax** [comment]
We need both because the user name serves as another semi-secret value. There is a much greater variation in the mapping of user name -> password that in email - password because users tend to use different user names for different services. This is especially true because user names are unique on each service.
